services:
  - type: web
    name: portal-nfse
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: HEADLESS
        value: "1"
      - key: TZ
        value: "America/Sao_Paulo"
